spring.application.name=SgOviProject

spring.datasource.type=org.springframework.jdbc.datasource.DriverManagerDataSource
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.jdbcUrl=jdbc:postgresql://db-aules.uji.es:5432/${DB}
spring.datasource.username=${USER}
spring.datasource.password=${PASS}


# Formato para las fechas en to_do el proyecto

# Para parámetros de URL (Spring MVC)
spring.mvc.format.date=dd-MM-yyyy

# Para el cuerpo JSON (Jackson)
spring.jackson.date-format=dd-MM-yyyy
