DROP TABLE IF EXISTS Communication;
DROP TABLE IF EXISTS Contract;
DROP TABLE IF EXISTS ActivityAssistance;

DROP TABLE IF EXISTS Candidacy;
DROP TABLE IF EXISTS Activity;

DROP TABLE IF EXISTS AssistanceRequest;

DROP TABLE IF EXISTS OviUser;
DROP TABLE IF EXISTS PapPati;
DROP TABLE IF EXISTS Instructor;

DROP TABLE IF EXISTS LegalGuardian;
DROP TABLE IF EXISTS Account;