package es.uji.ei1027.SgOviProject.dao;

import es.uji.ei1027.SgOviProject.model.AssistanceRequest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.DataRetrievalFailureException;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;
import org.springframework.stereotype.Repository;

import javax.sql.DataSource;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

@Repository
public class AssistanceRequestDao {

    private JdbcTemplate jdbcTemplate;

    @Autowired
    public void setDataSource(DataSource dataSource) {
        jdbcTemplate = new JdbcTemplate(dataSource);
    }

    // !!! Mirar como funciona un SERIAL !!!
    public int addAssistanceRequest(AssistanceRequest request) {

        // 1. Creamos el contenedor que atrapará la llave generada por PostgreSQL
        KeyHolder keyHolder = new GeneratedKeyHolder();

        // 2. Ejecutamos el update usando un PreparedStatementCreator (con una función lambda)
        jdbcTemplate.update(connection -> {
            PreparedStatement ps = connection.prepareStatement(
                    "INSERT INTO AssistanceRequest(dateRequest, assistantType, gender, city, yearsExperience, specifiedTrainings, initialDateRequired, monthsRequired, dniOviUser) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?)",
                    Statement.RETURN_GENERATED_KEYS); // ¡IMPORTANTE! Pedimos las claves

            ps.setObject(1, request.getDateRequest());
            ps.setString(2, request.getAssistantType().name());
            ps.setString(3, request.getGender());
            ps.setString(4, request.getCity());
            ps.setObject(5, request.getYearsExperience());
            ps.setString(6, request.getSpecifiedTrainings());
            ps.setObject(7, request.getInitialDateRequired());
            ps.setInt(8, request.getMonthsRequired());
            ps.setString(9, request.getDniOviUser());

            return ps;
        }, keyHolder); // Le pasamos el KeyHolder como segundo parámetro

        // 3. Extraemos el ID del KeyHolder
        Number key = keyHolder.getKey();

        if (key == null) {
            throw new DataRetrievalFailureException("Error al recuperar el ID autogenerado para AssistanceRequest.");
        }

        int autogeneratedId = key.intValue();
        request.setIdApRequest(autogeneratedId);

        return autogeneratedId;
    }

    public void deleteAssistanceRequest(int idApRequest) {
        jdbcTemplate.update("DELETE FROM AssistanceRequest WHERE idApRequest=?", idApRequest);
    }

    public void deleteAssistanceRequest(AssistanceRequest request) {
        jdbcTemplate.update("DELETE FROM AssistanceRequest WHERE idApRequest=?", request.getIdApRequest());
    }

    public void updateAssistanceRequest(AssistanceRequest request) {
        jdbcTemplate.update("UPDATE AssistanceRequest SET dateRequest=?, assistantType=?, gender=?, city=?, yearsExperience=?, specifiedTrainings=?, initialDateRequired=?, monthsRequired=?, dniOviUser=? WHERE idApRequest=?",
                request.getDateRequest(),
                request.getAssistantType().name(),
                request.getGender(),
                request.getCity(),
                request.getYearsExperience(),
                request.getSpecifiedTrainings(),
                request.getInitialDateRequired(),
                request.getMonthsRequired(),
                request.getDniOviUser(),
                request.getIdApRequest()); // El ID va al final para el WHERE
    }

    public AssistanceRequest getAssistanceRequest(int idApRequest) {
        try {
            return jdbcTemplate.queryForObject("SELECT * FROM AssistanceRequest WHERE idApRequest=?",
                    new AssistanceRequestRowMapper(), idApRequest);
        } catch(EmptyResultDataAccessException e) {
            return null;
        }
    }

    public List<AssistanceRequest> getAssistanceRequests() {
        try {
            return jdbcTemplate.query("SELECT * FROM AssistanceRequest",
                    new AssistanceRequestRowMapper());
        } catch (EmptyResultDataAccessException e) {
            return new ArrayList<AssistanceRequest>();
        }
    }

    public List<AssistanceRequest> getAssistanceRequestsByDni(String dniOviUser) {
        try {
            return jdbcTemplate.query("SELECT * FROM AssistanceRequest WHERE dniOviUser=?",
                    new AssistanceRequestRowMapper(), dniOviUser);
        } catch (EmptyResultDataAccessException e) {
            return new ArrayList<AssistanceRequest>();
        }
    }
}